# -*- coding: utf-8 -*-

# ToMaTo (Topology management software) 
# Copyright (C) 2010 Dennis Schwerdel, University of Kaiserslautern
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	(r'^$', 'tomato.main.index'),
	(r'^fonts/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'fonts'}),
	(r'^img/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'img'}),
	(r'^js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'js'}),
	(r'^style/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'style'}),
	(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'static'}),
	(r'^help$', 'tomato.help.help'),
	(r'^help/contact$', 'tomato.help.contact_form'),
	(r'^help/(?P<page>.*)$', 'tomato.help.help'),
	(r'^ticket$', 'tomato.main.ticket'),
	(r'^project$', 'tomato.main.project'),
	(r'^login$', 'tomato.main.login'),
	(r'^logout$', 'tomato.main.logout'),
	(r'^account/register$', 'tomato.account.register'),	
	url(r'^account/list$', 'tomato.account.list', {"organization": True}, name="account_list"),	
	url(r'^account/list/all$', 'tomato.account.list', {"organization": False}, name="account_list_all"),	
	url(r'^account/registrations$', 'tomato.account.list', {"organization": True, "with_flag": "new_account"}, name="account_list_registrations"),	
	url(r'^account/registrations/all$', 'tomato.account.list', {"organization": False, "with_flag": "new_account"}, name="account_list_registrations_all"),	
	url(r'^organization/(?P<organization>\w+)/accounts$', 'tomato.account.list', name="organization_accounts"),
	(r'^account$', 'tomato.account.info'),	
	(r'^account/(?P<id>[^/]*)$', 'tomato.account.info'),	
	(r'^account/(?P<id>[^/]*)/accept$', 'tomato.account.accept'),	
	(r'^account/(?P<id>[^/]*)/edit$', 'tomato.account.edit'),	
	(r'^account/(?P<id>[^/]*)/remove$', 'tomato.account.remove'),	
	url(r'^topology$', 'tomato.topology.list', {"show_all": False}, name="topology_list"),
	url(r'^topology/all$', 'tomato.topology.list', {"show_all": True}, name="topology_list_all"),
	url(r'^organization/(?P<organization>\w+)/topologies$', 'tomato.topology.list', {"show_all": True}, name="organization_topologies"),
	(r'^topology/(?P<id>\d+)$', 'tomato.topology.info'),
	(r'^topology/(?P<id>\d+)/export$', 'tomato.topology.export'),
	(r'^topology/(?P<id>\d+)/usage$', 'tomato.topology.usage'),
	(r'^topology/create$', 'tomato.topology.create'),
	(r'^topology/import$', 'tomato.topology.import_'),
	(r'^tutorial$', 'tomato.tutorial.list'),
	(r'^tutorial/start$', 'tomato.tutorial.start'),
	(r'^connection/(?P<id>\d+)/usage$', 'tomato.connection.usage'),
	(r'^element/(?P<id>\d+)/usage$', 'tomato.element.usage'),
	(r'^element/(?P<id>\d+)/rextfv_status$', 'tomato.element.rextfv_status'),
	(r'^element/(?P<id>\d+)/console$', 'tomato.element.console'),
	(r'^element/(?P<id>\d+)/console_novnc$', 'tomato.element.console_novnc'),
	(r'^map/$', 'tomato.site.map'),
	(r'^map.kml$', 'tomato.site.map_kml'),
	(r'^link_stats/(?P<site>\w+)$', 'tomato.site.details_site'),
	(r'^link_stats/(?P<src>\w+)/(?P<dst>\w+)$', 'tomato.site.details_link'),
	(r'^host/$', 'tomato.host.list'),
	(r'^host/add$', 'tomato.host.add'),
	(r'^host/edit/$', 'tomato.host.edit'),
	(r'^host/edit/(?P<address>.*)$', 'tomato.host.edit'),
	(r'^host/remove/$', 'tomato.host.remove'),
	(r'^host/remove/(?P<address>.*)$', 'tomato.host.remove'),
	(r'^organization/$', 'tomato.organization.list'),
	(r'^organization/add$', 'tomato.organization.add'),
	(r'^organization/(?P<name>\w+)$', 'tomato.organization.info'),
	(r'^organization/(?P<name>\w+)/edit$', 'tomato.organization.edit'),
	(r'^organization/(?P<name>\w+)/remove$', 'tomato.organization.remove'),
	(r'^organization/(?P<organization>\w+)/add_site$', 'tomato.site.add'),
	(r'^site/(?P<name>\w+)/edit$', 'tomato.site.edit'),
	(r'^site/(?P<name>\w+)/remove$', 'tomato.site.remove'),
	(r'^template/$', 'tomato.template.list'),
	(r'^template/add$', 'tomato.template.add'),
	(r'^template/edit/$', 'tomato.template.edit'),
	(r'^template/edit/(?P<res_id>\d+)$', 'tomato.template.edit'),
	(r'^template/edit/data$', 'tomato.template.edit_data'),
	(r'^template/edit/(?P<res_id>\d+)/data$', 'tomato.template.edit_data'),
	(r'^template/edit/torrent$', 'tomato.template.edit_torrent'),
	(r'^template/edit/(?P<res_id>\d+)/torrent$', 'tomato.template.edit_torrent'),
	(r'^template/remove/$', 'tomato.template.remove'),
	(r'^template/remove/(?P<res_id>\d+)$', 'tomato.template.remove'),
	(r'^profile/$', 'tomato.profile.list'),
	(r'^profile/add/$', 'tomato.profile.add'),
	(r'^profile/edit/$', 'tomato.profile.edit'),
	(r'^profile/edit/(?P<res_id>\d+)$', 'tomato.profile.edit'),
	(r'^profile/remove/$', 'tomato.profile.remove'),
	(r'^profile/remove/(?P<res_id>\d+)$', 'tomato.profile.remove'),
	(r'^external_network/$', 'tomato.external_network.list'),
	(r'^external_network/add/$', 'tomato.external_network.add'),
	(r'^external_network/edit/$', 'tomato.external_network.edit'),
	(r'^external_network/edit/(?P<res_id>\d+)$', 'tomato.external_network.edit'),
	(r'^external_network/remove/$', 'tomato.external_network.remove'),
	(r'^external_network/remove/(?P<res_id>\d+)$', 'tomato.external_network.remove'),
	(r'^external_network_instances/$', 'tomato.external_network_instances.index'),
	(r'^external_network_instances/add/$', 'tomato.external_network_instances.add'),
	(r'^external_network_instances/edit/$', 'tomato.external_network_instances.edit'),
	(r'^external_network_instances/edit/(?P<res_id>\d+)$', 'tomato.external_network_instances.edit'),
	(r'^external_network_instances/remove/$', 'tomato.external_network_instances.remove'),
	(r'^external_network_instances/remove/(?P<res_id>\d+)$', 'tomato.external_network_instances.remove'),
	(r'^ajax/topology/(?P<id>\d+)/info$', 'tomato.ajax.topology_info'),
	(r'^ajax/topology/(?P<id>\d+)/action$', 'tomato.ajax.topology_action'),
	(r'^ajax/topology/(?P<id>\d+)/modify$', 'tomato.ajax.topology_modify'),
	(r'^ajax/topology/(?P<id>\d+)/permission$', 'tomato.ajax.topology_permission'),
	(r'^ajax/topology/(?P<id>\d+)/remove$', 'tomato.ajax.topology_remove'),
	(r'^ajax/element/(?P<id>\d+)/info$', 'tomato.ajax.element_info'),
	(r'^ajax/topology/(?P<topid>\d+)/create_element$', 'tomato.ajax.element_create'),
	(r'^ajax/element/(?P<id>\d+)/action$', 'tomato.ajax.element_action'),
	(r'^ajax/element/(?P<id>\d+)/modify$', 'tomato.ajax.element_modify'),
	(r'^ajax/element/(?P<id>\d+)/remove$', 'tomato.ajax.element_remove'),
	(r'^ajax/element/(?P<id>\d+)/rextfv_status$', 'tomato.ajax.element_rextfv_status'),
	(r'^ajax/connection/(?P<id>\d+)/info$', 'tomato.ajax.connection_info'),
	(r'^ajax/connection/create$', 'tomato.ajax.connection_create'),
	(r'^ajax/connection/(?P<id>\d+)/action$', 'tomato.ajax.connection_action'),
	(r'^ajax/connection/(?P<id>\d+)/modify$', 'tomato.ajax.connection_modify'),
	(r'^ajax/connection/(?P<id>\d+)/remove$', 'tomato.ajax.connection_remove'),
	(r'^ajax/account/(?P<name>.*)/info', 'tomato.ajax.account_info'),
)
