# -*- coding: utf-8 -*-

import xmlrpclib

class Fault(xmlrpclib.Fault):
    pass

def new(code, text):
    return Fault(code, text)

UNKNOWN = -1
NO_SUCH_TOPOLOGY = 100
ACCESS_TO_TOPOLOGY_DENIED = 101
NOT_A_REGULAR_USER = 102
INVALID_TOPOLOGY_STATE_TRANSITION = 103
IMPOSSIBLE_TOPOLOGY_CHANGE = 104
TOPOLOGY_HAS_PROBLEMS = 105
MALFORMED_XML = 106
MALFORMED_TOPOLOGY_DESCRIPTION = 107
NO_SUCH_DEVICE = 108
UPLOAD_NOT_SUPPORTED = 109
DOWNLOAD_NOT_SUPPORTED = 110
INVALID_TOPOLOGY_STATE = 111
NO_SUCH_HOST = 200
NO_SUCH_HOST_GROUP = 201
ACCESS_TO_HOST_DENIED = 202
HOST_EXISTS = 203
NO_HOSTS_AVAILABLE = 204