Document: nlxtp-guest-modules
Title: Debian nlxtp-guest-modules Manual
Author: <insert document author here>
Abstract: This manual describes what nlxtp-guest-modules is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nlxtp-guest-modules/nlxtp-guest-modules.sgml.gz

Format: postscript
Files: /usr/share/doc/nlxtp-guest-modules/nlxtp-guest-modules.ps.gz

Format: text
Files: /usr/share/doc/nlxtp-guest-modules/nlxtp-guest-modules.text.gz

Format: HTML
Index: /usr/share/doc/nlxtp-guest-modules/html/index.html
Files: /usr/share/doc/nlxtp-guest-modules/html/*.html
